name: Deploy Auth Backend to VPS

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy Auth Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/sportsblog-auth-backend
            git reset --hard origin/master
            git clean -fd
            git pull origin master
            npm install
            pm2 restart sportsblog-auth-backend --update-env
